import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import confirmRouter from "./confirm.js";
import parentsRouter from "./parents.js";
import childrenRouter from "./children.js";
import matchingRouter from "./matching.js";
import matchesRouter from "./matches.js";
import statsRouter from "./stats.js";
import usersRouter from "./users.js";
import webhooksRouter from "./webhooks.js";
import onboardingRouter from "./onboarding.js";
import activityRouter from "./activity.js";
import syncRouter from "./sync.js";
import enrollRouter from "./enroll.js";
import giveAKeyRouter from "./give-a-key.js";
import slackRouter from "./slack.js";
import influencersRouter from "./influencers.js";
import packDeliveryRouter from "./pack-delivery.js";
import cancellationsRouter from "./cancellations.js";
import klaviyoSyncRouter from "./klaviyo-sync.js";
import lifecycleJobsRouter from "./lifecycle-jobs.js";
import emailTemplatesRouter from "./email-templates.js";
import coppaRouter from "./coppa.js";
import auditLogRouter from "./audit-log.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(confirmRouter);
router.use(webhooksRouter);
router.use(onboardingRouter);
router.use(syncRouter);
router.use(enrollRouter);
router.use(giveAKeyRouter);
router.use(authRouter);
router.use(parentsRouter);
router.use(childrenRouter);
router.use(matchingRouter);
router.use(matchesRouter);
router.use(statsRouter);
router.use(usersRouter);
router.use(activityRouter);
router.use(slackRouter);
router.use(influencersRouter);
router.use(packDeliveryRouter);
router.use(cancellationsRouter);
router.use(klaviyoSyncRouter);
router.use(lifecycleJobsRouter);
router.use(emailTemplatesRouter);
router.use(coppaRouter);
router.use(auditLogRouter);

export default router;
